version: "3"

services:
  creditrisk_server:
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - API_NAME=api
      - DB_URL=sqlite:///database.db
      - PORT=8080
    networks:
      main:
        aliases:
          - creditrisk_server

networks:
  main: