version: "3"

services:
  creditrisk_server:
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - API_NAME=api
      - DB_URL=postgresql://username:userpass@pg_main:5432/testdb
      - PORT=8080
    depends_on:
      - pg_main
    networks:
      main:
        aliases:
          - creditrisk_server
  
  pg_main:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: testdb        


networks:
  main: